#!/usr/bin/env python3
import random

def main():
    # Генерируем 4-значное число с разными цифрами
    while True:
        number = random.randint(1000, 9999)
        if len(set(str(number))) == 4:
            break

    print("Компьютер загадал 4-значное число")

    popit = 0

    while True:
        chislo = input("Ваш вариант: ")
